services:
  fluig:
    image: fluig-base:latest
    mem_limit: 6g
    mem_reservation: 3g
    build:
      context: ./setup
      dockerfile: Dockerfile
      args:
        - VERSAO_FLUIG=2.0.0
        - TZ=${TZ}
        - INSTALL_NODE=${INSTALL_NODE}
        - INSTALL_SOLR=${INSTALL_SOLR}
        - JAVA_XMS=${JAVA_XMS}
        - JAVA_XMX=${JAVA_XMX}
        - FLUIG_DB_USER=${FLUIG_DB_USER}
        - FLUIG_DB_PASS=${FLUIG_DB_PASS}
        - FLUIG_DB_HOST=${FLUIG_DB_HOST}
        - FLUIG_DB_PORT=${FLUIG_DB_PORT}
        - FLUIG_DB_NAME=${FLUIG_DB_NAME}
        - LS_HOST=${LS_HOST}
        - LS_PORT=${LS_PORT}
    container_name: fluig-app
    environment:
      TZ: ${TZ}
      JAVA_OPTS: >
        -${JAVA_XMS}
        -${JAVA_XMX}
        -XX:+UseG1GC
        -Dfile.encoding=UTF-8
        -Duser.timezone=${TZ}
        -Djava.net.preferIPv4Stack=true
    ulimits:
      nofile:
        soft: 65000
        hard: 65000    
    command: >
      bash -c "/usr/local/bin/start-fluig"        
    volumes:
      - fluig-volume:/opt/fluig-volume
      - fluig_deploy:/opt/fluig/appserver/standalone/deploy
      - fluig_log:/opt/fluig/appserver/standalone/log      
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - 8080:8080
      # Em ambiente de produção, evite expor portas administrativas e serviços internos
      # O Apache Solr (8983) e o Node (7777/8000) podem conversar na rede interna do Docker
      # - 8983:8983
      # - 9990:9990
    networks:
      - fluigNetwork
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.36
    container_name: fluig-mysql
    command: [
      "mysqld",
      "--lower_case_table_names=1",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci",
      "--default_storage_engine=InnoDB"
      "--default-time-zone=${TZ}"
      "--max_allowed_packet=256M"
    ]
    restart: unless-stopped
    ports:
      - 127.0.0.1:3305:3306 # O banco fica acessível externamente apenas pela própria máquina host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${FLUIG_DB_USER}
      MYSQL_PASSWORD: ${FLUIG_DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql     
    networks:
      - fluigNetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${FLUIG_DB_USER}", "-p${FLUIG_DB_PASS}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  mailpit:
    image: axllent/mailpit:latest
    container_name: fluig-mail
    environment:
      TZ: ${TZ}
    ports:
      - 8024:8025
      - 1024:1025
    networks:
      - fluigNetwork

networks:
  fluigNetwork:
    driver: bridge

volumes:
  fluig-volume:
    driver: local
  fluig_deploy:
    driver: local
  fluig_log:
    driver: local
  mysql_data:
    driver: local
